version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 597000290781.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodepipeline-devops-pucrs .
      - docker tag nodepipeline-devops-pucrs:latest 597000290781.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops-pucrs:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 597000290781.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops-pucrs:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nodepipeline-devops-avancado-cluster-ecs","imageUri":"%s"}]' 597000290781.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops-pucrs:latest > imagedefinitions.json
      #- printf '[{"name":"nodepipeline-devops-pucrs","imageUri":"%s"}]' 597000290781.dkr.ecr.us-east-1.amazonaws.com/nodepipeline-devops-pucrs:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json
